export {default as Navbar } from './navbar'
export {default as Footer } from './footer'
export {default as Product} from './product'
export {default as Bestselers } from './bestsellers'
export {default as Shipping } from './shipping'
export {default as OrderSummary } from './orderSum'
export {default as CartSlide} from './cart'
export {default as ProductImage} from './productImage'
export {default as SideNav } from './sidenav'
export {default as NewsLetter} from './newsletter'
export {default as ProductGrid} from './productsgrid'